spring:
  application:
    name: SpringSecurityJwtHomework
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jwt?serverVersion=16&charset=utf8
    username: jwt
    password: jwt

jwt:
  secret: faadd63584c84e672ff5824b4f85226faadd63584c84e672ff5824b4f85226
  accessTokenExpiration: 1m
  refreshTokenExpiration: 30m

server:
  servlet:
    context-path: /api/v1