spring:
    application:
        name: SpringSecurityJwtHomework
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/jwt?serverVersion=16&charset=utf8
        username: jwt
        password: jwt